source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'RealmDefaults_Tests' do
  pod 'RealmDefaults', :path => '../'


end

target 'RealmDefaults_Demo' do
  pod 'RealmDefaults', :path => '../'


end
