source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'RealmDefaults_Tests', :exclusive => true do
  pod 'RealmDefaults', :path => '../'

  
end

target 'RealmDefaults_Demo', :exclusive => true do
  pod 'RealmDefaults', :path => '../'

  
end
